-- Script chạy lần lượt các proc transform Landing -> Staging
USE DW_Synthea_Staging;
GO
EXEC dbo.usp_transform_landing_to_staging_patients;
EXEC dbo.usp_transform_landing_to_staging_encounters;
EXEC dbo.usp_transform_landing_to_staging_conditions;
EXEC dbo.usp_transform_landing_to_staging_medications;
EXEC dbo.usp_transform_landing_to_staging_observations;
EXEC dbo.usp_transform_landing_to_staging_procedures;
EXEC dbo.usp_transform_landing_to_staging_immunizations;
EXEC dbo.usp_transform_landing_to_staging_allergies;
EXEC dbo.usp_transform_landing_to_staging_careplans;
EXEC dbo.usp_transform_landing_to_staging_devices;
EXEC dbo.usp_transform_landing_to_staging_imaging_studies;
EXEC dbo.usp_transform_landing_to_staging_supplies;
EXEC dbo.usp_transform_landing_to_staging_organizations;
EXEC dbo.usp_transform_landing_to_staging_providers;
EXEC dbo.usp_transform_landing_to_staging_payers;
EXEC dbo.usp_transform_landing_to_staging_payer_transitions;
