-- Transform Landing_Payers to Staging_Payers (chuẩn hóa, làm sạch)
CREATE OR ALTER PROCEDURE dbo.usp_transform_landing_to_staging_payers
AS
BEGIN
    SET NOCOUNT ON; SET XACT_ABORT ON;
    BEGIN TRAN;
    BEGIN TRY
        IF OBJECT_ID(N'DW_Synthea_Landing.dbo.Landing_Payers', N'U') IS NULL
           OR OBJECT_ID(N'DW_Synthea_Staging.dbo.Staging_Payers', N'U') IS NULL
            THROW 50001, 'Missing required table: Landing_Payers or Staging_Payers.', 1;

        DROP TABLE IF EXISTS #src;

        SELECT
            LEFT(LTRIM(RTRIM(Id)),36) AS Id,
            NULLIF(LEFT(LTRIM(RTRIM(NAME)),255),'') AS NAME,
            NULLIF(LEFT(REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(ADDRESS)),'\r',' '),'\n',' '),'\t',' '),255),'') AS ADDRESS,
            NULLIF(LEFT(LTRIM(RTRIM(CITY)),100),'') AS CITY,
            NULLIF(LEFT(LTRIM(RTRIM(STATE_HEADQUARTERED)),50),'') AS STATE_HEADQUARTERED,
            NULLIF(LEFT(LTRIM(RTRIM(ZIP)),10),'') AS ZIP,
            NULLIF(LEFT(LTRIM(RTRIM(PHONE)),20),'') AS PHONE,
            TRY_CAST(NULLIF(AMOUNT_COVERED,'') AS DECIMAL(18,2)) AS AMOUNT_COVERED,
            TRY_CAST(NULLIF(AMOUNT_UNCOVERED,'') AS DECIMAL(18,2)) AS AMOUNT_UNCOVERED,
            TRY_CAST(NULLIF(REVENUE,'') AS DECIMAL(18,2)) AS REVENUE,
            TRY_CAST(NULLIF(COVERED_ENCOUNTERS,'') AS INT) AS COVERED_ENCOUNTERS,
            TRY_CAST(NULLIF(UNCOVERED_ENCOUNTERS,'') AS INT) AS UNCOVERED_ENCOUNTERS,
            TRY_CAST(NULLIF(COVERED_MEDICATIONS,'') AS INT) AS COVERED_MEDICATIONS,
            TRY_CAST(NULLIF(UNCOVERED_MEDICATIONS,'') AS INT) AS UNCOVERED_MEDICATIONS,
            TRY_CAST(NULLIF(COVERED_PROCEDURES,'') AS INT) AS COVERED_PROCEDURES,
            TRY_CAST(NULLIF(UNCOVERED_PROCEDURES,'') AS INT) AS UNCOVERED_PROCEDURES,
            TRY_CAST(NULLIF(COVERED_IMMUNIZATIONS,'') AS INT) AS COVERED_IMMUNIZATIONS,
            TRY_CAST(NULLIF(UNCOVERED_IMMUNIZATIONS,'') AS INT) AS UNCOVERED_IMMUNIZATIONS,
            TRY_CAST(NULLIF(UNIQUE_CUSTOMERS,'') AS INT) AS UNIQUE_CUSTOMERS,
            TRY_CAST(NULLIF(QOLS_AVG,'') AS DECIMAL(18,4)) AS QOLS_AVG,
            TRY_CAST(NULLIF(MEMBER_MONTHS,'') AS INT) AS MEMBER_MONTHS,
            batch_id,
            update_at
        INTO #src
        FROM DW_Synthea_Landing.dbo.Landing_Payers
        WHERE Id IS NOT NULL AND LTRIM(RTRIM(Id)) <> '';

        MERGE DW_Synthea_Staging.dbo.Staging_Payers AS t
        USING #src AS s
        ON t.Id = s.Id
        WHEN MATCHED AND (t.update_at < s.update_at) THEN
            UPDATE SET
                NAME = s.NAME,
                ADDRESS = s.ADDRESS,
                CITY = s.CITY,
                STATE_HEADQUARTERED = s.STATE_HEADQUARTERED,
                ZIP = s.ZIP,
                PHONE = s.PHONE,
                AMOUNT_COVERED = s.AMOUNT_COVERED,
                AMOUNT_UNCOVERED = s.AMOUNT_UNCOVERED,
                REVENUE = s.REVENUE,
                COVERED_ENCOUNTERS = s.COVERED_ENCOUNTERS,
                UNCOVERED_ENCOUNTERS = s.UNCOVERED_ENCOUNTERS,
                COVERED_MEDICATIONS = s.COVERED_MEDICATIONS,
                UNCOVERED_MEDICATIONS = s.UNCOVERED_MEDICATIONS,
                COVERED_PROCEDURES = s.COVERED_PROCEDURES,
                UNCOVERED_PROCEDURES = s.UNCOVERED_PROCEDURES,
                COVERED_IMMUNIZATIONS = s.COVERED_IMMUNIZATIONS,
                UNCOVERED_IMMUNIZATIONS = s.UNCOVERED_IMMUNIZATIONS,
                UNIQUE_CUSTOMERS = s.UNIQUE_CUSTOMERS,
                QOLS_AVG = s.QOLS_AVG,
                MEMBER_MONTHS = s.MEMBER_MONTHS,
                batch_id = s.batch_id,
                update_at = s.update_at
        WHEN NOT MATCHED BY TARGET THEN
            INSERT (Id,NAME,ADDRESS,CITY,STATE_HEADQUARTERED,ZIP,PHONE,AMOUNT_COVERED,AMOUNT_UNCOVERED,REVENUE,COVERED_ENCOUNTERS,UNCOVERED_ENCOUNTERS,COVERED_MEDICATIONS,UNCOVERED_MEDICATIONS,COVERED_PROCEDURES,UNCOVERED_PROCEDURES,COVERED_IMMUNIZATIONS,UNCOVERED_IMMUNIZATIONS,UNIQUE_CUSTOMERS,QOLS_AVG,MEMBER_MONTHS,create_at,update_at,batch_id)
            VALUES (s.Id,s.NAME,s.ADDRESS,s.CITY,s.STATE_HEADQUARTERED,s.ZIP,s.PHONE,s.AMOUNT_COVERED,s.AMOUNT_UNCOVERED,s.REVENUE,s.COVERED_ENCOUNTERS,s.UNCOVERED_ENCOUNTERS,s.COVERED_MEDICATIONS,s.UNCOVERED_MEDICATIONS,s.COVERED_PROCEDURES,s.UNCOVERED_PROCEDURES,s.COVERED_IMMUNIZATIONS,s.UNCOVERED_IMMUNIZATIONS,s.UNIQUE_CUSTOMERS,s.QOLS_AVG,s.MEMBER_MONTHS,SYSUTCDATETIME(),s.update_at,s.batch_id);

        DROP TABLE IF EXISTS #src;
        COMMIT;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK;
        DROP TABLE IF EXISTS #src;
        THROW;
    END CATCH
END
GO
