-- Script chạy lần lượt các proc transform Landing -> Staging
USE DW_Synthea_Staging;
GO
EXEC dbo.usp_transform_landing_to_staging_patients;
EXEC dbo.usp_transform_landing_to_staging_encounters;
EXEC dbo.usp_transform_landing_to_staging_conditions;
EXEC dbo.usp_transform_landing_to_staging_medications;
EXEC dbo.usp_transform_landing_to_staging_organizations;
EXEC dbo.usp_transform_landing_to_staging_providers;
EXEC dbo.usp_transform_landing_to_staging_payers;
EXEC dbo.usp_transform_landing_to_staging_payer_transitions;
